# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:

#Azure Resource Manager connection created during pipeline creation
azureSubscription: 'b1a402f7-c0b7-4f70-993e-2a4a1b40d67a'


#Function app name
functionAppName: 'gs1testdevopsas'


#Environment name
environmentName: 'gs1testdevopsas'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
